In [5]:
!pip install -q spacy gradio pandas

In [6]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 107.8 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [7]:
import spacy
import pandas as pd
import gradio as gr

In [8]:
nlp = spacy.load("en_core_web_sm")

print("NER model loaded successfully!")

NER model loaded successfully!

In [9]:
text = "Apple announced a new product in California on September 10, 2026."

doc = nlp(text)

print(text)

Apple announced a new product in California on September 10, 2026.

In [10]:
for ent in doc.ents:
    print(ent.text, "->", ent.label_)

Apple -> ORG
California -> GPE
September 10, 2026 -> DATE

In [11]:
for ent in doc.ents:
    print(
        "Entity:", ent.text,
        "| Label:", ent.label_,
        "| Meaning:", spacy.explain(ent.label_)
    )

Entity: Apple | Label: ORG | Meaning: Companies, agencies, institutions, etc.
Entity: California | Label: GPE | Meaning: Countries, cities, states
Entity: September 10, 2026 | Label: DATE | Meaning: Absolute or relative dates or periods

In [12]:
entities = []

for ent in doc.ents:
    entities.append({
        "Entity": ent.text,
        "Label": ent.label_,
        "Description": spacy.explain(ent.label_)
    })

df = pd.DataFrame(entities)

df

               Entity Label                              Description
0               Apple   ORG  Companies, agencies, institutions, etc.
1          California   GPE                Countries, cities, states
2  September 10, 2026  DATE    Absolute or relative dates or periods

In [13]:
text = """
Microsoft was founded in 1975.
The company is headquartered in Washington.
Satya Nadella became CEO in 2014.
"""

doc = nlp(text)

for ent in doc.ents:
    print(ent.text, "->", ent.label_)

Microsoft -> ORG
1975 -> DATE
Washington -> GPE
Satya Nadella -> PERSON
2014 -> DATE

In [14]:
from spacy import displacy

displacy.render(doc, style="ent", jupyter=True)

In [15]:
def extract_entities(text):
    doc = nlp(text)

    results = []

    for ent in doc.ents:
        results.append({
            "Entity": ent.text,
            "Label": ent.label_,
            "Description": spacy.explain(ent.label_) or "Unknown"
        })

    return pd.DataFrame(
        results,
        columns=["Entity", "Label", "Description"]
    )

In [16]:
sample_text = """
Google was founded in 1998.
Its headquarters are located in California.
The company developed several artificial intelligence products.
"""

result = extract_entities(sample_text)

result

       Entity Label                              Description
0      Google   ORG  Companies, agencies, institutions, etc.
1        1998  DATE    Absolute or relative dates or periods
2  California   GPE                Countries, cities, states

In [17]:
with gr.Blocks() as app:

    gr.Markdown("# 🔎 Named Entity Recognition")

    gr.Markdown(
        "Enter text below to identify people, organizations, "
        "locations, dates and other named entities."
    )

    text_input = gr.Textbox(
        label="Enter Text",
        placeholder="Enter a sentence or paragraph...",
        lines=6
    )

    analyze_button = gr.Button("Extract Entities")

    output = gr.Dataframe(
        headers=["Entity", "Label", "Description"],
        datatype=["str", "str", "str"],
        label="Detected Entities"
    )

    analyze_button.click(
        fn=extract_entities,
        inputs=text_input,
        outputs=output
    )

app.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://5763d19e0a91f05bb2.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)